# SPDX-FileCopyrightText: 2023 Andrew Pantuso <ajpantuso@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: server
images:
- name: server
  newName: ghcr.io/ajpantuso/server
  newTag: main
patchesStrategicMerge:
- ./10_server.Deployment.patch.yaml
resources:
- ./00_namespace.yaml
- ./10_server.Service.yaml
- ../../deploy
